/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApartamentosRouteImport } from './routes/apartamentos'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardChatRouteImport } from './routes/dashboard.chat'
import { Route as DashboardCitasRouteImport } from './routes/dashboard.citas'
import { Route as DashboardClientesRouteImport } from './routes/dashboard.clientes'
import { Route as DashboardConfiguracionRouteImport } from './routes/dashboard.configuracion'
import { Route as DashboardPerfilRouteImport } from './routes/dashboard.perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartamentosRoute = ApartamentosRouteImport.update({
  id: '/apartamentos',
  path: '/apartamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitasRoute = DashboardCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracionRoute = DashboardConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apartamentos': typeof ApartamentosRoute
  '/areas': typeof AreasRoute
  '/comercial': typeof ComercialRoute
  '/contacto': typeof ContactoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/citas': typeof DashboardCitasRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/configuracion': typeof DashboardConfiguracionRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apartamentos': typeof ApartamentosRoute
  '/areas': typeof AreasRoute
  '/comercial': typeof ComercialRoute
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/citas': typeof DashboardCitasRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/configuracion': typeof DashboardConfiguracionRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apartamentos': typeof ApartamentosRoute
  '/areas': typeof AreasRoute
  '/comercial': typeof ComercialRoute
  '/contacto': typeof ContactoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/citas': typeof DashboardCitasRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/configuracion': typeof DashboardConfiguracionRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apartamentos'
    | '/areas'
    | '/comercial'
    | '/contacto'
    | '/dashboard'
    | '/login'
    | '/registro'
    | '/dashboard/chat'
    | '/dashboard/citas'
    | '/dashboard/clientes'
    | '/dashboard/configuracion'
    | '/dashboard/perfil'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apartamentos'
    | '/areas'
    | '/comercial'
    | '/contacto'
    | '/login'
    | '/registro'
    | '/dashboard/chat'
    | '/dashboard/citas'
    | '/dashboard/clientes'
    | '/dashboard/configuracion'
    | '/dashboard/perfil'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/apartamentos'
    | '/areas'
    | '/comercial'
    | '/contacto'
    | '/dashboard'
    | '/login'
    | '/registro'
    | '/dashboard/chat'
    | '/dashboard/citas'
    | '/dashboard/clientes'
    | '/dashboard/configuracion'
    | '/dashboard/perfil'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApartamentosRoute: typeof ApartamentosRoute
  AreasRoute: typeof AreasRoute
  ComercialRoute: typeof ComercialRoute
  ContactoRoute: typeof ContactoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartamentos': {
      id: '/apartamentos'
      path: '/apartamentos'
      fullPath: '/apartamentos'
      preLoaderRoute: typeof ApartamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/citas': {
      id: '/dashboard/citas'
      path: '/citas'
      fullPath: '/dashboard/citas'
      preLoaderRoute: typeof DashboardCitasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracion': {
      id: '/dashboard/configuracion'
      path: '/configuracion'
      fullPath: '/dashboard/configuracion'
      preLoaderRoute: typeof DashboardConfiguracionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil': {
      id: '/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardCitasRoute: typeof DashboardCitasRoute
  DashboardClientesRoute: typeof DashboardClientesRoute
  DashboardConfiguracionRoute: typeof DashboardConfiguracionRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatRoute: DashboardChatRoute,
  DashboardCitasRoute: DashboardCitasRoute,
  DashboardClientesRoute: DashboardClientesRoute,
  DashboardConfiguracionRoute: DashboardConfiguracionRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApartamentosRoute: ApartamentosRoute,
  AreasRoute: AreasRoute,
  ComercialRoute: ComercialRoute,
  ContactoRoute: ContactoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
